---
on:
  - push
  - pull_request

jobs:
  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@v1
      - run: editorconfig-checker
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: bewuethr/shellcheck-action@v2
